import type { DeviceType } from './index.js'
import type { DeviceCommonOptions } from './generated/common-options.js'
import type { DeviceStatusDetail } from './deviceStatusDetail.js'

export enum StatusCode {
	UNKNOWN = 0, // Status unknown
	GOOD = 1, // All good and green
	WARNING_MINOR = 2, // Everything is not OK, operation is not affected
	WARNING_MAJOR = 3, // Everything is not OK, operation might be affected
	BAD = 4, // Operation affected, possible to recover
	FATAL = 5, // Operation affected, not possible to recover without manual interference
}
export interface DeviceStatus {
	statusCode: StatusCode
	/**
	 * Human-readable status messages generated by the device
	 *
	 * This is the primary way to consume device status information for display to users.
	 * The device automatically generates these messages, which may involve complex logic
	 * like pluralization, conditional formatting, or context-specific variations.
	 */
	messages: Array<string>

	/**
	 * Structured status details
	 *
	 * For advanced use cases requiring access to detailed information by the consuming application,
	 * for example to override default messages with custom templates. Each detail contains a code
	 * (e.g., 'DEVICE_ATEM_DISCONNECTED') and context for message interpolation (e.g., { host:
	 * '192.168.1.10' }). Use this when you need to override default messages or access structured
	 * data. See `interpolateTemplateString()` and `statusDetailsToMessages()` for custom template
	 * utilities.
	 *
	 * Status details are optional and may not be provided by all devices. If not provided, the
	 * consumer should rely solely on the `messages` array for status information.
	 *
	 * When provided, the entries in the array should correspond directly to the `messages` array,
	 * meaning that each message at index `i` is generated based on the status detail at index `i`.
	 */
	statusDetails?: Array<DeviceStatusDetail>
	active: boolean
}

export interface DeviceOptionsBase<TType extends DeviceType, TOptions> extends SlowReportOptions, DeviceCommonOptions {
	type: TType
	isMultiThreaded?: boolean
	reportAllCommands?: boolean
	options?: TOptions
}

export interface SlowReportOptions {
	/** If set, report back that a command was slow if not sent at this time */
	limitSlowSentCommand?: number
	/** If set, report back that a command was slow if not fullfilled (sent + ack:ed) at this time */
	limitSlowFulfilledCommand?: number
}
